/// <reference path='Demo/Interface/IUrvashiScope.ts'/>
/// <reference path='Demo/Models/UserUrvashi.ts'/>
/// <reference path='Demo/Services/IUserServiceUrvashi.ts' />
/// <reference path='Demo/Services/UserServiceUrvashi.ts' />
/// <reference path='Demo/Services/IFileUploadServiceUrvashi.ts' />
/// <reference path='Demo/Services/FileUploadServiceUrvashi.ts' />
/// <reference path='Demo/Controller/BaseControllerUrvashi.ts' />
/// <reference path='Demo/Controller/UserControllerUrvashi.ts' />
/// <reference path='Demo/Controller/ModalInstanceControllerUrvashi.ts' />
/// <reference path='Demo/Directive/FileUploadDirectiveUrvashi.ts' />
/// <reference path='Demo/DemoAppUrvashi.ts' /> 
